#!/bin/sh
# run from /wrangling
# extracts log likelihood data from output files generated by cmdstanr
set -eu -o pipefail

TDIR=../stats/model-out-data_$1

FILES=($(ls $TDIR | grep 04_.*csv))

head -70 $TDIR"/"${FILES[0]} |
    sed -e '/^#/d' - |
    awk 'BEGIN{FS = ","}{for (i = 1; i <= NF; i++) {
        if ($i ~ /log_lik/) print $i}}' - > 05_ll-cols.txt

echo "Making tmp directory" $TDIR"/tmp"

mkdir $TDIR/tmp

for file in $FILES
    do
        echo "Getting" $file
        cp $file $TDIR/tmp/

        echo "Cleaning comments with sed."
        sed -i -e '/^#/d' $TDIR/tmp/$(basename $file)

        printf "\n\n>>>>>>>>>> Running R script.\n\n"
        Rscript 05_extract-loglik.R --args $TDIR/tmp/$(basename $file) $1

        printf "\n\n>>>>>>>>>> Removing file copy from tmp.\n\n"
        rm $TDIR/tmp/$(basename $file)
done

echo "Cleaning temp folder."
rm -r $TDIR/tmp
